### ISSUE TITLE
What JavaScript micro:bit editor are you using?

### ISSUE THREAD

**Issue by will-moore** [andrew-t/microbit#2]
Hi, I just enjoyed playing your tetris game by downloading the hex file.
It plays really well and it quite a heroic effort given the limitations on JS on the micro:bit.
But I when I tried to copy & paste your code into the PXT or CodeKingdoms JavaScript editors I get errors with all the ```#``` lines E.g. ```# LET %MAX = 4```. Are you using some different editor?
Or do these just need removing?
 Thanks!

**Comment by andrew-t** [comment]
I'm using the official editor, but I do some pre-processing on the script. I use Node for that, so I actually end up with Javascript writing Javascript, but in short, [https://github.com/andrew-t/microbit/blob/master/js/compile.js](compile.js) turns all the `# LET %MAX = 4` stuff into real JS.

It's because the JS on micro:bit is somewhat limited, and can't (say) handle arrays. The actual code I paste into the online editor is [https://github.com/andrew-t/microbit/blob/master/js/output/tetris.js](here), and you can see in there how I emulate arrays. You can probably also see why I wrote the shorter version and expanded it automatically.

All of that said, if you want to do something complex enough to require arrays, it might be that micropython is a better choice.

**Comment by will-moore** [comment]
Nice, thanks!
I still can't believe that JS on the micro:bit doesn't even handle arrays. Such a shame as I'd love to use it as a way to teach JavaScript.

**Comment by andrew-t** [comment]
Yeah. I mean it's not really Javascript at all to be honest, it's such a small subset. It's more like C. There is a C compiler now; it wasn't released when I did this. The whole toolchain is pretty big though.
